spring:
  mongodb:
    uri: mongodb://localhost:27017/healthsafe
    database: healthsafe
  graphql:
    graphiql:
      enabled: true

management:
  endpoint:
    health:
      show-details: always

aws:
  region: ap-south-1
  healthlake:
    datastore-endpoint: https://healthlake.ap-south-1.amazonaws.com/datastore/8beccfc1f6ca1e8419ae9f29e5a46be5/r4/
  s3:
    bucket: healthsafe-shl-ap-south-1

app:
  encryption-key: dev-encryption-key-32bytes-long!!
  base-url: http://localhost:8080
  cors:
    allowed-origins: http://localhost:3000
